---
categories:
- ""
- ""
date: "2020-10-20"
description: ""
draft: false
keywords: ""
slug: blog1
title: "COVID-19 Data Insights"
output: html_document
---



```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
library(scales)
```

Let us look at CDC Covid-19 Case Surveillance Data. There are well over 3 million entries of individual, de-identified patient data.

```{r, cache=TRUE}

# URL link to CDC to download data
url <- "https://data.cdc.gov/api/views/vbim-akqf/rows.csv?accessType=DOWNLOAD"

covid_data <- vroom(url)%>%
  clean_names()

# covid_data <- read_csv(here::here('data', 'COVID-19_Case_Surveillance_Public_Use_Data.csv.zip')) %>% 
#   clean_names()
```

Given the data we have, I would produce two graphs that show death % rate:

## 1. by age group, sex, and whether the patient had co-morbidities or not

```{r}
covid_chart_one <- covid_data %>% 
  # Manually delete data with values that are "Missing", "Unknown" as well as "Other" for gender
  filter(sex != "Missing" &
           sex != "Unknown" &
           sex != "Other" &
           age_group != "Missing" &
           age_group != "Unknown" &
           medcond_yn != "Missing" &
           medcond_yn != "Unknown" &
           death_yn != "Missing" &
           death_yn != "Unknown") %>% 
  group_by(sex, medcond_yn, age_group) %>% 
  summarize(death_rate = count(death_yn == "Yes")/n()*100, .group = "keep") %>% 
  mutate(medcond_yn = as.factor(medcond_yn)) # Calculation of death_rate 
# We will reorder the medical condition for when we facet the chart later
covid_chart_one$medcond_yn <- relevel(covid_chart_one$medcond_yn, "Yes", "No")

new_labels1 <- c("No" = "Without comorbidities", "Yes" = "With Comorbidities") # build a new vector to change strip label

  
ggplot(covid_chart_one, aes(x = age_group, 
                            y = death_rate))+
  geom_col(fill = "#6879a1")+
  # add data label
  geom_text(aes(label = round(death_rate, 1)), 
            hjust = 0, 
            size = 2.5)+ 
  coord_flip()+
  # Fixes scale and format of numbers of y axis
  scale_y_continuous(labels = function(death_rate)paste0(death_rate, "%"), 
                    breaks = seq(0, 60, 20),
                    limits = c(0, 70))+ # set axis limits and change breaks
  theme_bw()+
  theme(axis.title = element_blank(), # delete axis title
        text = element_text(size = 8))+ # Change text size
  labs(title = "Covid death % by age group, sex, and presence of co-morbidities",
       caption = "Source: CDC")+
  facet_grid(medcond_yn ~ sex, labeller = labeller(medcond_yn = new_labels1)) # create faceted chart and rename strip name

```


## 2. by age group, sex, and whether the patient was admited to Intensive Care Unit (ICU) or not.
```{r}
covid_chart2 <- covid_data%>% 
  # Manually delete data with values that are "Missing", "Unknown" as well as "Other" for gender
  filter(sex != "Missing" &
           sex != "Unknown" &
           sex != "Other" &
           age_group != "Missing" &
           age_group != "Unknown" &
           medcond_yn != "Missing" &
           medcond_yn != "Unknown" &
           icu_yn != "Missing" &
           icu_yn != "Unknown") %>% 
  group_by(sex, icu_yn, age_group) %>% 
  summarize(death_rate = count(death_yn == "Yes")/n()*100,  .group = "keep") %>% # Calculation of death_rate 
  mutate(icu_yn = as.factor(icu_yn))

# We will reorder the ICU column for when we facet the chart later
covid_chart2$icu_yn <- relevel(covid_chart2$icu_yn, "Yes", "No")

# create a new vector to change strip label
new_labels2 <- c("No" = "No ICU", "Yes" = "Admitted to ICU") 

  
ggplot(covid_chart2, aes(x = age_group, 
                         y = death_rate))+
  geom_col(fill = "#ff9582")+
  geom_text(aes(label=round(death_rate, 1)), # add data label
            hjust = 0, # change label position
            size = 2.5)+ # change label font size 
  coord_flip()+
  scale_y_continuous(labels = function(death_rate)paste0(death_rate, "%"), # change axis labels to percent format
                     breaks = seq(0, 80, 20),
                     limits = c(0, 85))+ # set axis limits and change breaks
  theme_bw()+
  theme(axis.title = element_blank(), # delete axis title
        text = element_text(size = 8), # Change text size
        
        )+
  labs(title = "Covid death % by age group, sex, and whether patient was admitted to ICU",
       caption = "Source: CDC")+
  facet_grid(icu_yn ~ sex, labeller = labeller(icu_yn = new_labels2)) # create faceted chart and rename strip name

```
